version: 2

# YAML anchors for common configurations
common: &common
  reviewers:
    - "awslabs/lisa-maintainers"
  commit-message:
    prefix: "chore"
    include: "scope"

pip-config: &pip-config
  <<: *common
  package-ecosystem: "pip"
  schedule:
    interval: "weekly"
    day: "tuesday"
    time: "09:00"
  open-pull-requests-limit: 5

docker-config: &docker-config
  <<: *common
  package-ecosystem: "docker"
  schedule:
    interval: "weekly"
    day: "thursday"
    time: "09:00"
  open-pull-requests-limit: 3

updates:
  # Enable version updates for npm
  - <<: *common
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  # Pip directories
  - <<: *pip-config
    directory: "/"
  - <<: *pip-config
    directory: "/lisa-sdk"
  - <<: *pip-config
    directory: "/lib/core/layers/authorizer"
  - <<: *pip-config
    directory: "/lib/core/layers/common"
  - <<: *pip-config
    directory: "/lib/core/layers/fastapi"
  - <<: *pip-config
    directory: "/lib/serve/rest-api/src"
  - <<: *pip-config
    directory: "/lib/rag/layer"

  # GitHub Actions
  - <<: *common
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5

  # Docker directories
  - <<: *docker-config
    directory: "/lib/rag/ingestion/ingestion-image"
  - <<: *docker-config
    directory: "/lib/rag/vector-store/state_machine"
  - <<: *docker-config
    directory: "/lib/serve/rest-api"
  - <<: *docker-config
    directory: "/lib/serve/mcp-workbench"
  - <<: *docker-config
    directory: "/lib/serve/ecs-model/vllm"
  - <<: *docker-config
    directory: "/lib/serve/ecs-model/embedding/tei"
  - <<: *docker-config
    directory: "/lib/serve/ecs-model/embedding/instructor"
  - <<: *docker-config
    directory: "/lib/serve/ecs-model/textgen/tgi"
