name: Auto-Generate PR Description

on:
  pull_request:
    types: [opened]
    branches: ['develop']

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-pr-description:
    name: Generate PR Description
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.ts
            **/*.js
            **/*.yaml
            **/*.yml
            **/*.json
            **/*.md

      - name: Make script executable
        run: chmod +x .github/scripts/generate-pr-description.sh

      - name: Generate PR description
        id: generate-description
        run: |
          .github/scripts/generate-pr-description.sh "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Read generated description
        id: read-description
        run: |
          echo "DESCRIPTION<<EOF" >> $GITHUB_OUTPUT
          cat description.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const currentBody = pullRequest.body || '';
            const generatedDescription = `${{ steps.read-description.outputs.DESCRIPTION }}`;

            // Only update if the current description is empty or very short
            if (currentBody.length < 50) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: generatedDescription
              });

              console.log('PR description updated successfully');
            } else {
              console.log('PR already has a description, skipping update');
            }
