name: Merge Main into Develop

on:
  release:
    types: [released]

permissions:
  contents: read  # Default read-only

jobs:
  conduct_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for merging branches
    steps:
      - name: Checkout main
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: main
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
      - name: merge main into develop
        run: |
          git config --global user.email "evmann@amazon.com"
          git config --global user.name "github_actions_lisa"
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/main -m "Auto-merge main back to develop post release"
          git push --force origin develop
  send_final_slack_notification:
    name: Send Final Slack Notification
    needs: [conduct_merge]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Notification that Develop is up to date
        uses: rtCamp/action-slack-notify@cdf0a2130cbcdfd82ba5fcac8e076370bf381b36 # v2
        env:
          SLACK_WEBHOOK: ${{ secrets.INTERNAL_DEV_SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ contains(join(needs.*.result, ' '), 'failure') && 'failure' || 'success' }}
          SLACK_TITLE: 'Main merged into Develop'
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_MESSAGE_ON_FAILURE: '<!here> New Release has been <${{ github.event.release.html_url }}|published>! FAILED to merge main into Develop.'
          SLACK_MESSAGE_ON_SUCCESS: '<!here> New Release has been <${{ github.event.release.html_url }}|published>! Main was SUCCESSFULLY merged into Develop.'
          SLACK_MESSAGE: '<!here> New Release has been <${{ github.event.release.html_url }}|published>! Merging main into develop finished with status ${{ job.status }}.'
