name: 'Dependency Review'
on: [pull_request_target]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      pull-requests: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          # Only checkout the base branch, not the PR code
          ref: ${{ github.base_ref }}
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
        with:
          # Only review dependencies, don't execute PR code
          fail-on-severity: moderate
