name: Comprehensive SAST Security Scanning

on:
  push:
    branches: [ "main", "develop", "release/**", "hotfix/**", "feature/**" ]
  pull_request:
    branches: [ "main", "develop", "release/**", "hotfix/**", "feature/**" ]
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM

permissions:
  contents: read
  security-events: write

jobs:
  python-security-scan:
    name: Python Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e ./lisa-sdk

      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json
          bandit -r . -f txt -o bandit-report.txt

      - name: Run Safety Check
        run: |
          pip install safety
          safety check --json --output safety-report.json || true

      - name: Upload Python Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: python-security-reports
          path: |
            bandit-report.json
            bandit-report.txt
            safety-report.json
          retention-days: 30

  javascript-security-scan:
    name: JavaScript/TypeScript Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Security Scan
        run: |
          npm run lint
          npx eslint --ext .js,.ts,.jsx,.tsx . --format json --output-file eslint-report.json

      - name: Run NPM Audit
        run: |
          npm audit --audit-level=moderate --json > npm-audit-report.json || true

      - name: Upload JavaScript Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: javascript-security-reports
          path: |
            eslint-report.json
            npm-audit-report.json
          retention-days: 30

  infrastructure-security-scan:
    name: Infrastructure Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run CDK-NAG Security Scan
        run: |
          npx cdk-nag --output-format json --output-file cdk-nag-report.json || true

      - name: Upload Infrastructure Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure-security-reports
          path: cdk-nag-report.json
          retention-days: 30

  security-report-aggregation:
    name: Security Report Aggregation
    runs-on: ubuntu-latest
    needs: [python-security-scan, javascript-security-scan, infrastructure-security-scan]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all security reports
        uses: actions/download-artifact@v4
        with:
          path: security-reports

      - name: Generate Security Summary
        run: |
          echo "# Security Scan Summary" > security-summary.md
          echo "Generated on: $(date)" >> security-summary.md
          echo "" >> security-summary.md
          
          if [ -f "security-reports/python-security-reports/bandit-report.json" ]; then
            echo "## Python Security (Bandit)" >> security-summary.md
            echo "- Scan completed successfully" >> security-summary.md
          fi
          
          if [ -f "security-reports/javascript-security-reports/eslint-report.json" ]; then
            echo "## JavaScript Security (ESLint)" >> security-summary.md
            echo "- Scan completed successfully" >> security-summary.md
          fi
          
          if [ -f "security-reports/infrastructure-security-reports/cdk-nag-report.json" ]; then
            echo "## Infrastructure Security (CDK-NAG)" >> security-summary.md
            echo "- Scan completed successfully" >> security-summary.md
          fi

      - name: Upload Security Summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.md
          retention-days: 30
